### ISSUE TITLE
新版本依然有传送bug

### ISSUE THREAD

**Issue by 9Vcc** [SkyDynamic/Regamemode_Helper#2]
这个新版本!c也有传送bug，二次!Clear是不会传送了，但是切换旁观之后飞到想要传送的地方在!c一次会覆盖第一次!c生成的坐标文件然后!s就照成传送了，解决方法可以在!c时加个判断，判断玩家是否为旁观或者生存，若为旁观则不生成坐标文件覆盖第一次!c时生成的坐标文件，若为生存则正常获取坐标切换旁观

**Comment by SkyDynamic** [comment]
抱歉，现在才看到这个issues（github没给咱推）
现在已经放弃mcdr了，转用Mod的方式。
详见: [CameraMod](https://github.com/SkyDynamic/CameraMod)
